### ISSUE TITLE
Could not login to the new user site

### ISSUE THREAD

**Issue by zarnecki** [GLORIA-project/users-hub-interface#2]
Today at about 8:30 PM I logged into new GLORIA Users portal:
     http://ws.users.gloria-project.eu:8080/
and made reservation for 2 slots (15' each) night observations at BART.
However, when I tried to use the slots, at 10PM, I could not log into this page
any more...

Regards
   Filip

**Comment by fserena** [comment]
Thank you Filip. I will investigate this. Can you try to login again please?
By the way... are you blocking the cookies?

**Comment by lnicastro** [comment]
Definitely needs a check in the JS source code: JS and cookies unblocked.

**Comment by fserena** [comment]
Same problem Luciano?

**Comment by zarnecki** [comment]
Hi,

I think I understood the problem, or at least how to reproduce/avoid it.
I wrote you that I could login without problems the first time.
When I tried again, Firefox filled username and password for me.
And this is the problem. When I filled BOTH username and password by hand 
it worked. One has to write username by hand as well, even if what Firefox 
proposes looks OK. It looks OK, but you will not be able to login unless 
you write it again by hand...

It is strange, I never had such a situation before, but at least I know 
how to avoid it...

Regards
   Filip

On Thu, 30 Jan 2014, Fernando Serena wrote:

> Same problem Luciano?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/GLORIA-project/UsersHub/issues/2#issuecomment-33667763

---

```
  prof. dr hab. A.F.Zarnecki
     Division of Particles
  and Fundamental Interactions
Institute of Experimental Physics
```

Faculty of Physics, University of Warsaw
      Hoza 69, 00-681 Warszawa
              POLAND

   tel: (+4822) 5532365      http://www.fuw.edu.pl/~zarnecki
   fax: (+4822) 5532106      e-mail:  zarnecki@fuw.edu.pl

---

**Comment by fserena** [comment]
Ok, I will try to reproduce the situation and look for a solution so you don't need to avoid it again :+1: 
I label this issue as "bug".

**Comment by fserena** [comment]
This bug should be removed. Please Filip, test it again and let me know.

**Comment by ReneHudec** [comment]
Login failed = something is wrong

**Comment by zarnecki** [comment]
It is solved for me. No problem any more...

**Comment by ReneHudec** [comment]
It is NOT solved. Login is still impossible, at least for me.

Rene

**Comment by fserena** [comment]
Rene, you should create an account first.

I consider this issue solved.

**Comment by ReneHudec** [comment]
I have created an account, of course.

Regards rene
