### ISSUE TITLE
Registro de usuarios de pruebas para experimentos nocturnos

### ISSUE THREAD

**Issue by carlibiri** [GLORIA-project/users-hub-interface#25]
Según he hablado con Alberto, una buena opción para lo comentado en la última reunión que tuvimos, podría ser añadir un campo en el formulario de alta en el que los usuarios que vayan a ser testers pongan una contraseña que se les proporcione y de esta forma se le puedan dar a estos acceso a los experimentos de teleoperación de telescopios nocturnos.

Ya me decís cómo lo véis.

Un saludo.

**Comment by fserena** [comment]
Lo veo bien, pero si te parece retomamos la discusión de como implementarlo más adelante.

**Comment by carlibiri** [comment]
La cierro y si más adelante hiciera falta la volvemos a abrir.
