### ISSUE TITLE
No se puede entrar con Google Chrome

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/users-hub-interface#29]
No se puede entrar a GLORIA con Chrome.
![28-05-2014 fallo web gloria](https://cloud.githubusercontent.com/assets/6812954/3111249/f4a5de52-e6ae-11e3-9e97-ea2d09b98341.jpg)
![28-05-2014 usuario no vlido en chrome](https://cloud.githubusercontent.com/assets/6812954/3111250/f4aab13e-e6ae-11e3-8156-dc5a0bb624f8.jpg)

**Comment by angelagonzalez** [comment]
Después de intentar 4-5 veces sí ha entrado.

**Comment by angelagonzalez** [comment]
Y ahora otra vez no entra con Chrome (he salido e intentado volver a entrar).

**Comment by angelagonzalez** [comment]
Bueno, al parecer mi navegador tenía mal recordada la contraseña. Creo que se puede cerrar este issue. Disculpas.

**Comment by fserena** [comment]
La alerta que te ha salido inicialmente puede deberse a que el navegador estaba cacheando contenido obsoleto de la web o a que has interrumpido la carga de la página con un reload.

Para futuros problemas de inicio de sesión, si sólo ocurre con un navegador, lo más probable es que se deba a una contraseña errónea. 

Avisaremos cuando cambiemos algo de la funcionalidad del login para probarlo intensivamente en todos los navegadores. Desde hace semanas no ha cambiado nada al respecto.
