### ISSUE TITLE
Opción de selección varia en el planificador y errores

### ISSUE THREAD

**Issue by ghost** [GLORIA-project/users-hub-interface#33]
Para reservar o buscar un telescopio apropiado a tus necesidades, necesitas especificar algunos aspectos más de los que el planificador te deja seleccionar. Por ejemplo, yo quiero un tiempo de exposición de 0.01 a 60 segundos. Eso no es posible, ya que si escribes "[0.01 , 60] segundos" te aparece como error. También deberían haber opciones de indiferencia, es decir, ningún filtro específico o tiempo de exposición. Simplemente, seleccionar el mejor momento para experimentar con el planeta con los filtros que antes estén disponibles y cualquier tiempo de exposición.
Un saludo y gracias por crear esta magnífica y educativa herramienta.

**Comment by esgg** [comment]
La idea del tiempo de exposición es poner un sólo valor númerico, por tanto, no se aceptan intervalos. El intervalo que aparece por defecto es para mostrar el rango de funcionamiento. La idea del filtro es muy interesante, se lo comentaré al equipo de desarrollo.

Gracias por los ánimos y por las indicaciones.

**Comment by ghost** [comment]
Entonces, ¿el tiempo de exposición es específico? Porque me gustaría
informarme en qué telescopio puedo fotografiar Júpiter y cuándo, sin tener
que especificar dicho valor. ¿Hay alguna herramienta que  facilite esta
información? Como sugerencia, podríais poner alguna indicación en cada
telescopio. Por ejemplo: se pueden ver "x" objetos este día con este
telescopio.
¡Un saludo!

**Comment by esgg** [comment]
Tienes dos opciones para observar un objeto: 
- Indicando el tiempo de exposición, para Júpiter es mejor utilizar uno pequeño, menos de 1 segundo. Este valor depende del telescopio que se te asigne.
- Indicando la Magnitud y el SNR. Para el SNR prueba con un valor bajo, por ejemplo, 10. 

Como herramienta te recomiendo el Stellarium es bastante completo y muy útil. Con este programa podrás conocer también las magnitudes de los objetos celestes.

El planificador funciona asignándote un telescopio que cumpla las restricciones indicadas en el formulario. Además, el telescopio ejecuta el plan cuando lo considera oportuno, habrás visto que no se puede indicar un día en concreto. Esto dificulta la posibilidad de implementar la sugerencia.

No obstante lo consultaré con mis compañeros de cara a implementar algún mecanismo parecido al que sugieres que facilite las observaciones.

Muchas gracias por los comentarios!!

**Comment by ghost** [comment]
Gracias a vosotros por las indicaciones. ¡Saludos!
