### ISSUE TITLE
Telescopios y tiempo de uso

### ISSUE THREAD

**Issue by ccacnoa** [GLORIA-project/users-hub-interface#34]
Hace dias que me conecto para reservar en alguno de los telescopios posibles y casi nunca hay utilizarlo. Lo he venido comprobando con todos los telescopios y varios días.

Sabeis si hay alguna incidencia?

Gracias

**Comment by esgg** [comment]
Buenos días.

Uno de los telescopios BOOTES-2, no tiene red desde hace varios días.

El tiempo meteorológico de la pasada semana fue muy malo, por lo que no se pudieron abrir los telescopios. Si colocas el cursor sobre una reserva en la pantalla de reservas pendientes, verás que existe alarma de tiempo meteorológico. 

En concreto, en el Observatorio de El Teide, la pasada semana el viento alcanzó los 150kmh!!

Esperemos que vuelva el buen tiempo. 

En Chile (telescopio CATA 500) hace buen tiempo. Te recomendamos que uses el experimento del planificador. No podrás conectarte en tiempo real pero obtendrás imágenes muy espectaculares.

Gracias por el interés

**Comment by ccacnoa** [comment]
Muchas gracias por la información

Un saludo

Carmen
