### ISSUE TITLE
Falta de filtro Sloan u' en el telescopio REM

### ISSUE THREAD

**Issue by caiux** [GLORIA-project/users-hub-interface#35]
Parece que el telescopio REM no tiene el filtro Sloan u' (http://www.rem.inaf.it/zeropoint.html). ¿Podría por favor corregir la página web de GLOARIA? Muchas gracias.

**Comment by esgg** [comment]
Paso la incidencia a la persona responsable. Muchas gracias por el aviso.

**Comment by esgg** [comment]
Hemos eliminado el filtro de la página web de GLORIA. 
Gracias por la notificación
