### ISSUE TITLE
password requirements are not accurate

### ISSUE THREAD

**Issue by JunCTionS** [GLORIA-project/users-hub-interface#5]
Although the password requirements are only stated as:

"At least 6 characters containing a letter and number"
It seems to require also an upper case letter.

To reproduce the issue I tried to create the account:
username: testing123
e-mail: testing@123.com
password: thisisvalid1

failed and easily succeded when changing the first letter of the password ( Thisisvalid1 )

(feel free to delete said account)

**Comment by fserena** [comment]
Thank you! We will fix the message soon.

**Comment by fserena** [comment]
Done!
