### ISSUE TITLE
Language to be used

### ISSUE THREAD

**Issue by FrancescoAdi** [GLORIA-project/users-hub-interface#50]
Dear All,
I saw that expecially on this interface the majority of the discussions are started in Spanish.
Now, being Italian for me it's not a problem to understand this foreign Language due to a little experience with it, but the same Language can be a strong wall and barrier against other EU possibile users.
What about exchanging all info in ENGLISH?

**Comment by esgg** [comment]
Ciao, 

in principle, we answer all messages in github in the same language of the question. But, i agree with you, we should use English too. I will try to do it next time.

Grazie.
