### ISSUE TITLE
Can't access with a new user

### ISSUE THREAD

**Issue by JunCTionS** [GLORIA-project/users-hub-interface#9]
Any new user I have tried to create today was accepted but when attempting to access the system with those credentials it would give the error: "Usuario no valido" in Spanish and simply "Login failed" in English.

These accounts have received the link by e-mail and have been validated, also a new password has been requested and the new password received produces the same results.

I can still access the site with old credentials.

(Sorry if this is note code but database related, but I don't know where to submit that)

**Comment by fserena** [comment]
Thanks, we will investigate it as soon as possible. Alias?

**Comment by JunCTionS** [comment]
erm... forgot, but it's easy to replicate.  I did it again using a throwaway e-mail service.
e-mail: probandogloria@binkmail.com
user: probando123

**Comment by JunCTionS** [comment]
Update: now new users are accepted again, however the password used when registering doesn't work and I had to request a new password. Changing this password did work (by the way, [issue #7](https://github.com/GLORIA-project/UsersHub/issues/7) could be closed now, good work on that).

**Comment by fserena** [comment]
Thank you! Now it is working again.
